spring:
  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
