INSERT INTO AUTHOR(NAME) VALUES('JACK LONDON');

INSERT INTO GENRE(NAME) VALUES('Adventure literature');

INSERT INTO BOOK(NAME, AUTHOR_ID, GENRE_ID)
    SELECT
        'Martin Eden'
        , CURRENT VALUE FOR SEC_AUTHOR
        , CURRENT VALUE FOR SEC_GENRE;

INSERT INTO BOOK(NAME, AUTHOR_ID, GENRE_ID)
    SELECT
        'The Little Lady'
        , CURRENT VALUE FOR SEC_AUTHOR
        , CURRENT VALUE FOR SEC_GENRE;
